package glorydark.gui;

public enum guitype {
    MainMenu,
    TeleportInitiativeMENU,
    TeleportPassiveMENU,
    TeleportMainMenu,
    AcceptListInitiativeMENU,
    AcceptListPassiveMENU,
    WarpMenu,
    SettingMenu,
    ErrorMenu,
    WarpsSettingMenu,
    WarpSettingDownMenu,
    WarpsSettingManageMenu,
    WarpsSettingCreateMenu,
    WarpsSettingDeleteMenu,
    HomeMainMenu,
    HomeTeleportMenu,
    HomeDeleteMenu,
    HomeCreateMenu,
    MainSETTINGMENU,
    WorldTeleportMenu,
    ManagerWorldMenu,
}
