传送邀请花费: 10.0
设置家花费: 10.0
世界白名单:
  - world
  - abc
  - xsfb
设置重生点花费: 1000.0
版本号: 20210504
帮助:
  - '------ Mytp Manual ------'
  - /mytp open 打开操作gui界面
  - /mytp 添加白名单 <玩家昵称> 给予该玩家的白名单(可使用传送插件的高级功能)
  - /mytp 删除白名单 <玩家昵称> 移除该玩家的白名单(可使用传送插件的高级功能)
  - /mytp help 查看帮助
  - /mytp addwwl 地图名称 玩家昵称 (后台进行)
  - /mytp delwwl 地图名称 玩家昵称 (后台进行)
  - '------ Mytp Manual ------'
是否使用快捷工具: true
快捷工具ID: 347
是否启用打开音效: true