世界白名单:
  - world
  - abc
  - xsfb
版本号: 20210805
帮助:
  - '------ Mytp Manual ------'
  - /mytp open 打开操作gui界面
  - /mytp 添加白名单 <玩家昵称> 给予该玩家的白名单(可使用传送插件的高级功能)
  - /mytp 删除白名单 <玩家昵称> 移除该玩家的白名单(可使用传送插件的高级功能)
  - /mytp help 查看帮助
  - '------ Mytp Manual ------'
是否使用快捷工具: true
快捷工具ID: 347
是否启用打开音效: true
最多同时存在家: 5
随机传送世界:
  - "world"
设置家世界:
  - "world"
传送邀请花费: 10.0
设置家花费: 10.0
设置重生点花费: 1000.0
开启设置重生点: false
返回死亡点花费: 1000.0
随机传送花费: 0.0